# Generated by Django 5.2.3 on 2025-10-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('Orders', 'Orders'), ('Bookings', 'Bookings'), ('Reviews', 'Reviews')], max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
